import { StudioConfig } from '../types/studio-config'

export const GLOW_AESTHETICS: StudioConfig = {
    vertical: 'aesthetics',
    identity: {
        name: 'Glow Aesthetics',
        slug: 'glow-aesthetics',
        tagline: 'Advanced Aesthetics \u2022 Skin Clinic \u2022 London',
        artistName: 'Dr. Sarah Chen',
    },
    treatments: {
        menu: [
            {
                name: 'Lip Filler',
                slug: 'lip-filler',
                durationMins: 45,
                priceRange: '\u00a3250\u2013\u00a3450',
                depositAmount: 5000,
                consultRequired: false,
                category: 'injectables',
            },
            {
                name: 'Anti-Wrinkle (Botox)',
                slug: 'anti-wrinkle',
                durationMins: 30,
                priceRange: '\u00a3200\u2013\u00a3350',
                depositAmount: 5000,
                consultRequired: false,
                category: 'injectables',
            },
            {
                name: 'Dermal Filler',
                slug: 'dermal-filler',
                durationMins: 60,
                priceRange: '\u00a3300\u2013\u00a3600',
                depositAmount: 7500,
                consultRequired: true,
                category: 'injectables',
            },
            {
                name: 'Chemical Peel',
                slug: 'chemical-peel',
                durationMins: 45,
                priceRange: '\u00a3150\u2013\u00a3300',
                depositAmount: 5000,
                consultRequired: false,
                category: 'skin',
            },
            {
                name: 'Microneedling',
                slug: 'microneedling',
                durationMins: 60,
                priceRange: '\u00a3200\u2013\u00a3400',
                depositAmount: 5000,
                consultRequired: false,
                category: 'skin',
            },
        ],
        medicalFlagInstructions: 'If a client mentions pregnancy, breastfeeding, autoimmune conditions, blood thinners, or active skin infections, flag for practitioner review immediately. Do NOT proceed with booking.',
        pretreatmentInstructions: 'Avoid alcohol, aspirin, and ibuprofen for 48 hours before treatment. No retinol products for 3 days before skin treatments.',
        aftercareInstructions: 'Avoid touching the treated area for 4 hours. No strenuous exercise for 24 hours. Avoid extreme heat (sauna, sunbeds) for 48 hours.',
    },
    theme: {
        background: '220 20% 4%',
        foreground: '220 10% 96%',
        accent: '340 45% 65%',
        accentForeground: '220 20% 4%',
        mutedForeground: '220 10% 63%',
        dimmedForeground: '220 10% 42%',
        border: '220 15% 12%',
        card: '220 18% 8%',
        accentRgb: '199, 120, 150',
        ring: '340 45% 65%',
    },
    seo: {
        title: 'Glow Aesthetics | Advanced Skin Clinic London',
        description: 'Expert aesthetics treatments including lip filler, Botox, dermal fillers, and advanced skin treatments. Book your appointment today.',
        keywords: ['Aesthetics Clinic', 'London', 'Lip Filler', 'Botox', 'Dermal Filler', 'Skin Treatments', 'Chemical Peel'],
        openGraph: {
            title: 'Glow Aesthetics | Advanced Skin Clinic London',
            description: 'Expert aesthetics treatments including lip filler, Botox, dermal fillers, and advanced skin treatments.',
            type: 'website',
            locale: 'en_GB',
            url: 'https://www.apexink.uk/glow-aesthetics',
            siteName: 'Glow Aesthetics',
            images: [
                {
                    url: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&h=630&fit=crop&q=80',
                    width: 1200,
                    height: 630,
                    alt: 'Glow Aesthetics Clinic',
                },
            ],
        },
    },
    nav: {
        links: [
            { label: 'Treatments', href: '#sessions' },
            { label: 'Results', href: '#work' },
            { label: 'FAQ', href: '#faq' },
        ],
        bookButtonText: 'Book Now',
    },
    hero: {
        headline: ['Advanced', 'Aesthetics'],
        subheadline: 'Expert treatments tailored to your goals. From subtle enhancements to transformative results, every appointment starts with a conversation.',
        urgencyText: 'Limited availability this month',
        ctaText: 'Book a Consultation',
        image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&h=1000&fit=crop&q=80',
        imageAlt: 'Modern aesthetics clinic interior',
    },
    trustMetrics: {
        items: [
            { iconName: 'CheckCircle2', label: 'CQC Registered' },
            { iconName: 'Award', label: 'Level 7 Qualified' },
            { iconName: 'Shield', label: 'Fully Insured' },
            { iconName: 'Clock', label: 'Same-Week Appointments' },
        ],
    },
    portfolio: {
        sectionTitle: 'Results',
        subtitle: 'Real results from real clients. Every treatment is personalised to achieve natural-looking outcomes.',
        images: [
            'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop&q=80',
            'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=600&fit=crop&q=80',
            'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=600&fit=crop&q=80',
            'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&h=600&fit=crop&q=80',
            'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=600&h=600&fit=crop&q=80',
            'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=600&fit=crop&q=80',
        ],
    },
    sessions: {
        sectionTitle: 'Treatments',
        subtitle: 'All treatments carried out by qualified medical professionals. Consultations available for first-time clients.',
        items: [
            {
                iconName: 'Zap',
                title: 'Lip Filler',
                duration: '45 min',
                price: '\u00a3250',
                priceSubtitle: 'from',
                features: ['Hyaluronic acid filler', 'Natural-looking volume', 'Numbing cream included', 'Results last 6\u201312 months'],
                status: 'available',
                availabilityText: 'Next week',
                buttonText: 'Book Lip Filler',
                popular: true,
                buttonVariant: 'default',
            },
            {
                iconName: 'Clock',
                title: 'Anti-Wrinkle (Botox)',
                duration: '30 min',
                price: '\u00a3200',
                priceSubtitle: 'from',
                features: ['Forehead, frown lines, crow\u2019s feet', 'Quick treatment', 'No downtime', 'Results in 7\u201314 days'],
                status: 'available',
                availabilityText: 'This week',
                buttonText: 'Book Anti-Wrinkle',
                buttonVariant: 'outline',
            },
            {
                iconName: 'Calendar',
                title: 'Chemical Peel',
                duration: '45 min',
                price: '\u00a3150',
                priceSubtitle: 'from',
                features: ['Skin resurfacing', 'Reduces pigmentation', 'Improves texture', 'Course of 3 recommended'],
                status: 'available',
                availabilityText: 'Next week',
                buttonText: 'Book Chemical Peel',
                buttonVariant: 'outline',
            },
        ],
        guarantee: 'Free consultation for first-time clients. No treatment will proceed without your full informed consent.',
        popularLabel: 'Most Popular',
        waitlistButtonText: 'Join Waitlist',
    },
    socialProof: {
        sectionTitle: 'What Our Clients Say',
        testimonials: [
            {
                quote: 'Dr. Chen made me feel completely at ease. The results are so natural \u2014 exactly what I wanted.',
                author: 'Emma T.',
                city: 'London',
                rating: 5,
            },
            {
                quote: 'Best clinic experience I\u2019ve had. Professional, clean, and the booking process was seamless.',
                author: 'Sophie L.',
                city: 'London',
                rating: 5,
            },
            {
                quote: 'I was nervous about my first treatment but the whole team put me at ease. Highly recommend.',
                author: 'Rachel K.',
                city: 'London',
                rating: 5,
            },
        ],
        trustBadges: [
            { iconName: 'CheckCircle2', label: 'CQC Registered' },
            { iconName: 'TrendingUp', label: '500+ Treatments' },
            { iconName: 'Sparkles', label: 'Premium Products' },
            { iconName: 'Star', label: '4.9 Rating' },
        ],
        instagram: {
            label: '@glowaesthetics',
            images: [
                'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=400&fit=crop&q=80',
                'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=400&h=400&fit=crop&q=80',
                'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400&h=400&fit=crop&q=80',
                'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400&h=400&fit=crop&q=80',
            ],
        },
    },
    about: {
        sectionTitle: 'About the Clinic',
        paragraphs: [
            'Glow Aesthetics is a CQC-registered clinic in central London, led by Dr. Sarah Chen. With over 8 years of experience in aesthetics medicine, Dr. Chen specialises in natural-looking enhancements that enhance your features without changing who you are.',
            'Every treatment begins with a thorough consultation. We take the time to understand your goals, assess your suitability, and create a personalised treatment plan. No pressure, no upselling \u2014 just honest advice from a qualified medical professional.',
            'We use only premium, CE-marked products from trusted manufacturers. Your safety and satisfaction are our absolute priority.',
        ],
        callout: 'Consultations are always free for new clients.',
        image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&h=800&fit=crop&q=80',
        imageAlt: 'Glow Aesthetics clinic treatment room',
    },
    faq: {
        sectionTitle: 'Frequently Asked Questions',
        items: [
            {
                id: 'faq-1',
                question: 'Is there a consultation before treatment?',
                answer: 'Yes. All first-time clients receive a free consultation where we discuss your goals, assess suitability, and explain the treatment in detail. No treatment proceeds without your informed consent.',
            },
            {
                id: 'faq-2',
                question: 'How much does lip filler cost?',
                answer: 'Lip filler starts from \u00a3250 for 0.5ml and \u00a3350\u2013\u00a3450 for 1ml. The exact amount depends on your goals and what we recommend during your consultation.',
            },
            {
                id: 'faq-3',
                question: 'What qualifications does Dr. Chen have?',
                answer: 'Dr. Chen holds a Level 7 qualification in Aesthetic Medicine, is a registered medical practitioner with the GMC, and has completed advanced training in dermal fillers and anti-wrinkle treatments.',
            },
            {
                id: 'faq-4',
                question: 'Is there any downtime after treatment?',
                answer: 'Most treatments have minimal downtime. You may experience mild swelling or bruising for 24\u201348 hours. We provide detailed aftercare instructions with every treatment.',
            },
            {
                id: 'faq-5',
                question: 'Do you take a deposit?',
                answer: 'Yes, we take a \u00a350 deposit to secure your appointment. This is deducted from your treatment cost on the day. Deposits are refundable with 48 hours\u2019 notice.',
            },
            {
                id: 'faq-6',
                question: 'What products do you use?',
                answer: 'We exclusively use premium, CE-marked products including Juvederm, Restylane, and Allergan Botox. We never use unbranded or imported products.',
            },
        ],
    },
    finalCta: {
        headline: 'Ready to book?',
        subheadline: 'Free consultation for first-time clients. No commitment, just an honest conversation about your goals.',
        ctaText: 'Book Your Consultation',
    },
    booking: {
        modalTitle: 'Book Your Appointment',
        modalDescription: 'Select your treatment and preferred date. A \u00a350 deposit secures your slot.',
        successTitle: 'Booking Request Received',
        successMessage: 'We\u2019ll confirm your appointment within a few hours. Check your email for next steps.',
        submitText: 'Request Appointment',
        depositDisclaimer: 'I understand a \u00a350 deposit is required to confirm my appointment. This is deducted from the treatment cost. Refundable with 48 hours\u2019 notice.',
    },
    contact: {
        email: 'hello@glowaesthetics.co.uk',
        instagram: '@glowaesthetics',
        instagramUrl: 'https://instagram.com/glowaesthetics',
        phone: '020 7946 0958',
        address: '42 Harley Street, London W1G 9PL',
    },
    footer: {
        copyrightHolder: 'Glow Aesthetics Ltd',
        tagline: 'CQC Registered \u2022 Fully Insured \u2022 Level 7 Qualified',
    },
    blurDataUrl: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWEREiMxUf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54teleA/9k=',
}
