import { StudioConfig } from '../types/studio-config'

export const INKD_LONDON: StudioConfig = {
    identity: {
        name: 'INK\'D London',
        slug: 'inkd-london',
        tagline: 'Where London Gets Inked',
        artistName: 'Marcus Rivera',
    },
    theme: {
        background: '0 0% 4%',
        foreground: '60 9% 98%',
        accent: '210 100% 60%',
        accentForeground: '60 9% 98%',
        mutedForeground: '24 5% 64%',
        dimmedForeground: '12 6% 45%',
        border: '20 6% 12%',
        card: '20 6% 6%',
        accentRgb: '51, 153, 255',
        ring: '210 100% 60%',
    },
    seo: {
        title: 'INK\'D London - Premium Tattoo Studio in London',
        description: 'London\'s premier tattoo studio specializing in custom designs. Expert artists, sterile environment, and exceptional artistry in the heart of London.',
        keywords: ['tattoo studio London', 'custom tattoos London'],
        openGraph: {
            title: 'INK\'D London - Where London Gets Inked',
            description: 'Premium tattoo studio in London offering custom designs by expert artists. Book your consultation today.',
            type: 'website',
            locale: 'en_US',
            url: 'https://www.apexaisystems.co.uk/inkd-london',
            siteName: 'INK\'D London',
            images: [
                {
                    url: 'https://placehold.co/1200x630?text=INK%E2%80%99D%20London+OG',
                    width: 1200,
                    height: 630,
                    alt: 'INK\'D London',
                },
            ],
        },
    },
    nav: {
        links: [
            { label: 'Work', href: '#work' },
            { label: 'Sessions', href: '#sessions' },
            { label: 'FAQ', href: '#faq' },
        ],
        bookButtonText: 'Book Consultation',
    },
    hero: {
        headline: ['London\'s Premier', 'Tattoo Experience'],
        subheadline: 'Custom designs crafted by award-winning artists in the heart of London',
        urgencyText: 'Limited slots available this month',
        ctaText: 'Book Your Session',
        image: 'https://placehold.co/800x1000?text=Hero+Image',
        imageAlt: 'Professional tattoo artist at work in INK\'D London studio',
    },
    trustMetrics: {
        items: [
            { iconName: 'CheckCircle2', label: '8+ Years Experience' },
            { iconName: 'Zap', label: '1500+ Tattoos Done' },
            { iconName: 'Award', label: '5-Star Rated Studio' },
            { iconName: 'Shield', label: 'Custom Designs Only' },
        ],
    },
    portfolio: {
        sectionTitle: 'Our Latest Work',
        subtitle: 'Each piece tells a unique story, crafted with precision and artistic vision',
        images: [
            'https://placehold.co/600x600?text=Portfolio+1',
            'https://placehold.co/600x600?text=Portfolio+2',
            'https://placehold.co/600x600?text=Portfolio+3',
            'https://placehold.co/600x600?text=Portfolio+4',
            'https://placehold.co/600x600?text=Portfolio+5',
            'https://placehold.co/600x600?text=Portfolio+6',
        ],
    },
    sessions: {
        sectionTitle: 'Book Your Session',
        subtitle: 'Professional tattoo services tailored to your vision',
        guarantee: '100% satisfaction guarantee - we perfect your vision',
        popularLabel: 'Most Popular',
        waitlistButtonText: 'Join Waitlist',
        items: [
            {
                iconName: 'Zap',
                title: 'Consultation & Small Piece',
                duration: '2-3 hours',
                price: '£200',
                priceSubtitle: 'Perfect for first tattoos',
                features: ['Design consultation included', 'Up to 4 inch piece'],
                status: 'limited',
                availabilityText: 'Available this week',
                buttonText: 'Book Small Session',
                popular: false,
                buttonVariant: 'outline',
            },
            {
                iconName: 'Clock',
                title: 'Full Custom Session',
                duration: '4-6 hours',
                price: '£450',
                priceSubtitle: 'For detailed artwork',
                features: ['Complete custom design', 'Multiple revisions included'],
                status: 'available',
                availabilityText: 'Next available: 2 weeks',
                buttonText: 'Book Full Session',
                popular: true,
                buttonVariant: 'default',
            },
        ],
    },
    socialProof: {
        sectionTitle: 'What Our Clients Say',
        testimonials: [
            {
                quote: 'Marcus transformed my vision into an incredible piece of art. The attention to detail and professionalism at INK\'D London is unmatched.',
                author: 'Sarah Mitchell',
                city: 'Camden, London',
                rating: 5,
            },
            {
                quote: 'Best tattoo experience I\'ve ever had. The studio is immaculate and the artwork speaks for itself. Highly recommend INK\'D London.',
                author: 'James Thompson',
                city: 'Shoreditch, London',
                rating: 5,
            },
        ],
        trustBadges: [
            { iconName: 'CheckCircle2', label: 'Licensed Studio' },
            { iconName: 'TrendingUp', label: 'Award Winning' },
            { iconName: 'Sparkles', label: 'Sterile Environment' },
            { iconName: 'Star', label: 'Custom Designs' },
        ],
        instagram: {
            label: 'Follow on Instagram @inkdlondon',
            images: [
                'https://placehold.co/400x400?text=Insta+1',
                'https://placehold.co/400x400?text=Insta+2',
                'https://placehold.co/400x400?text=Insta+3',
                'https://placehold.co/400x400?text=Insta+4',
            ],
        },
    },
    about: {
        sectionTitle: 'Meet Your Artist',
        paragraphs: [
            'Marcus Rivera has been creating exceptional tattoo art in London for over 8 years. Specializing in neo-traditional and realism styles, Marcus brings each client\'s vision to life with meticulous attention to detail and artistic flair.',
            'At INK\'D London, we believe every tattoo should be a masterpiece. Our state-of-the-art studio maintains the highest standards of cleanliness and professionalism, ensuring your experience is as memorable as your new ink.',
        ],
        callout: 'Every piece is a collaboration between artist and client, resulting in truly unique artwork that tells your story.',
        image: 'https://placehold.co/600x800?text=Artist+Portrait',
        imageAlt: 'Marcus Rivera, lead tattoo artist at INK\'D London',
    },
    faq: {
        sectionTitle: 'Frequently Asked Questions',
        items: [
            {
                id: 'faq-1',
                question: 'How do I book a consultation?',
                answer: 'You can book directly through our website or contact us via Instagram. We recommend booking 2-3 weeks in advance for custom pieces.',
            },
            {
                id: 'faq-2',
                question: 'What\'s included in the consultation fee?',
                answer: 'The consultation includes design discussion, sizing, placement advice, and a custom sketch. This fee is applied toward your final tattoo session.',
            },
        ],
    },
    finalCta: {
        headline: 'Ready to Get Inked?',
        subheadline: 'Book your consultation today and let\'s bring your vision to life',
        ctaText: 'Start Your Journey',
    },
    booking: {
        modalTitle: 'Book Your Session',
        modalDescription: 'Fill out the form below and we\'ll get back to you within 24 hours to confirm your appointment.',
        successTitle: 'Booking Submitted!',
        successMessage: 'We\'ll contact you within 24 hours to confirm your appointment details.',
        submitText: 'Submit Booking',
        depositDisclaimer: 'A £50 deposit is required to secure your appointment',
    },
    contact: {
        email: 'hello@inkdlondon.co.uk',
        instagram: '@inkdlondon',
        instagramUrl: 'https://instagram.com/inkdlondon',
        phone: '+44 20 7123 4567',
        address: '123 Camden High Street, London NW1 7JR',
    },
    footer: {
        copyrightHolder: 'INK\'D London',
        tagline: 'Where London Gets Inked',
    },
    blurDataUrl: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWEREiMxUf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q==',
}
