import { StudioConfig } from '../types/studio-config'

export const TATTOO_SHOP_BY_DAN_GOLD: StudioConfig = {
    identity: {
        name: 'Tattoo Shop By Dan Gold',
        slug: 'tattoo-shop-by-dan-gold',
        tagline: 'Premium Custom Tattoos with Golden Touch',
        artistName: 'Dan Gold',
    },
    theme: {
        background: '0 0% 3%',
        foreground: '60 9% 98%',
        accent: '45 93% 47%',
        accentForeground: '60 9% 98%',
        mutedForeground: '24 5% 64%',
        dimmedForeground: '12 6% 45%',
        border: '20 6% 15%',
        card: '20 6% 6%',
        accentRgb: '218, 165, 32',
        ring: '45 93% 47%',
    },
    seo: {
        title: 'Tattoo Shop By Dan Gold - Premium Custom Tattoo Studio',
        description: 'Professional custom tattoos by Dan Gold. Award-winning artist specializing in unique designs. Book your consultation today for premium tattoo artistry.',
        keywords: ['custom tattoos Dan Gold', 'premium tattoo studio'],
        openGraph: {
            title: 'Tattoo Shop By Dan Gold - Premium Custom Tattoo Studio',
            description: 'Professional custom tattoos by Dan Gold. Award-winning artist specializing in unique designs. Book your consultation today for premium tattoo artistry.',
            type: 'website',
            locale: 'en_US',
            url: 'https://www.apexink.uk/tattoo-shop-by-dan-gold',
            siteName: 'Tattoo Shop By Dan Gold',
            images: [
                {
                    url: 'https://placehold.co/1200x630?text=Tattoo%20Shop%20By%20Dan%20Gold+OG',
                    width: 1200,
                    height: 630,
                    alt: 'Tattoo Shop By Dan Gold',
                },
            ],
        },
    },
    nav: {
        links: [
            { label: 'Work', href: '#work' },
            { label: 'Sessions', href: '#sessions' },
            { label: 'FAQ', href: '#faq' },
        ],
        bookButtonText: 'Book Consultation',
    },
    hero: {
        headline: ['Premium Custom Tattoos', 'With the Golden Touch'],
        subheadline: 'Transform your vision into stunning body art with Dan Gold\'s award-winning craftsmanship and attention to detail',
        urgencyText: 'Limited consultation slots available this month',
        ctaText: 'Book Your Design Session',
        image: 'https://placehold.co/800x1000?text=Hero+Image',
        imageAlt: 'Dan Gold creating a custom tattoo design',
    },
    trustMetrics: {
        items: [
            { iconName: 'CheckCircle2', label: '12+ Years Experience' },
            { iconName: 'Zap', label: '3000+ Custom Tattoos' },
            { iconName: 'Award', label: 'Award-Winning Artist' },
            { iconName: 'Shield', label: '100% Custom Designs' },
        ],
    },
    portfolio: {
        sectionTitle: 'Masterpiece Gallery',
        subtitle: 'Each tattoo tells a unique story, crafted with precision and artistic excellence',
        images: [
            'https://placehold.co/600x600?text=Portfolio+1',
            'https://placehold.co/600x600?text=Portfolio+2',
            'https://placehold.co/600x600?text=Portfolio+3',
            'https://placehold.co/600x600?text=Portfolio+4',
            'https://placehold.co/600x600?text=Portfolio+5',
            'https://placehold.co/600x600?text=Portfolio+6',
        ],
    },
    sessions: {
        sectionTitle: 'Tattoo Sessions',
        subtitle: 'Choose the perfect session for your tattoo journey',
        guarantee: '100% satisfaction guarantee on all custom designs',
        popularLabel: 'Most Popular',
        waitlistButtonText: 'Join Waitlist',
        items: [
            {
                iconName: 'Zap',
                title: 'Design Consultation',
                duration: '90 minutes',
                price: '£150',
                priceSubtitle: 'Includes custom design',
                features: ['Complete design consultation', 'Custom artwork creation'],
                status: 'limited',
                availabilityText: 'Available this week',
                buttonText: 'Book Consultation',
                popular: false,
                buttonVariant: 'outline',
            },
            {
                iconName: 'Clock',
                title: 'Full Tattoo Session',
                duration: '4-6 hours',
                price: '£450',
                priceSubtitle: 'Complete tattoo experience',
                features: ['Full tattoo completion', 'Aftercare kit included'],
                status: 'available',
                availabilityText: 'Next available slot',
                buttonText: 'Book Full Session',
                popular: true,
                buttonVariant: 'default',
            },
        ],
    },
    socialProof: {
        sectionTitle: 'What Our Clients Say',
        testimonials: [
            {
                quote: 'Dan\'s attention to detail is incredible. My tattoo exceeded all expectations and the healing process was perfect.',
                author: 'Sarah Mitchell',
                city: 'London',
                rating: 5,
            },
            {
                quote: 'The most professional tattoo experience I\'ve ever had. Dan\'s artistic vision brought my idea to life beautifully.',
                author: 'James Thompson',
                city: 'Manchester',
                rating: 5,
            },
        ],
        trustBadges: [
            { iconName: 'CheckCircle2', label: 'Licensed Professional' },
            { iconName: 'TrendingUp', label: 'Health & Safety Certified' },
            { iconName: 'Sparkles', label: 'Award Winner 2023' },
            { iconName: 'Star', label: '5-Star Rated Studio' },
        ],
        instagram: {
            label: 'Follow on Instagram @tattooshopbydangold',
            images: [
                'https://placehold.co/400x400?text=Insta+1',
                'https://placehold.co/400x400?text=Insta+2',
                'https://placehold.co/400x400?text=Insta+3',
                'https://placehold.co/400x400?text=Insta+4',
            ],
        },
    },
    about: {
        sectionTitle: 'Meet Dan Gold',
        paragraphs: [
            'With over 12 years of experience in the tattoo industry, Dan Gold has established himself as one of the most sought-after custom tattoo artists. His passion for creating unique, meaningful artwork has earned him recognition and a loyal clientele who appreciate his meticulous attention to detail.',
            'Dan specializes in bringing clients\' visions to life through collaborative design sessions, ensuring each tattoo is a perfect reflection of personal style and story. His commitment to excellence extends beyond artistry to include the highest standards of hygiene and client care.',
        ],
        callout: 'Every tattoo is a collaboration between artist and client, resulting in truly one-of-a-kind artwork.',
        image: 'https://placehold.co/600x800?text=Artist+Portrait',
        imageAlt: 'Dan Gold, professional tattoo artist',
    },
    faq: {
        sectionTitle: 'Frequently Asked Questions',
        items: [
            {
                id: 'faq-1',
                question: 'How far in advance should I book?',
                answer: 'We recommend booking 2-4 weeks in advance for consultation sessions and 4-8 weeks for full tattoo sessions. Popular time slots fill up quickly, so early booking ensures you get your preferred date.',
            },
            {
                id: 'faq-2',
                question: 'What\'s included in the consultation?',
                answer: 'Your consultation includes a detailed discussion of your vision, custom design creation, placement advice, and aftercare instructions. The £150 consultation fee is credited toward your full tattoo session when booked.',
            },
        ],
    },
    finalCta: {
        headline: 'Ready for Your Custom Tattoo?',
        subheadline: 'Book your consultation today and start your journey to exceptional body art',
        ctaText: 'Book Now',
    },
    booking: {
        modalTitle: 'Book Your Session',
        modalDescription: 'Choose your preferred session type and we\'ll contact you within 24 hours to confirm your booking.',
        successTitle: 'Booking Request Sent!',
        successMessage: 'We\'ll contact you within 24 hours to confirm your appointment and discuss your tattoo ideas.',
        submitText: 'Send Booking Request',
        depositDisclaimer: 'A £50 deposit is required to secure your booking',
    },
    contact: {
        email: 'hello@tattooshopbydangold.com',
        instagram: '@tattooshopbydangold',
        instagramUrl: 'https://instagram.com/tattooshopbydangold',
        phone: '+44 7123 456789',
        address: 'Professional Studio Location, UK',
    },
    footer: {
        copyrightHolder: 'Tattoo Shop By Dan Gold',
        tagline: 'Premium Custom Tattoos with Golden Touch',
    },
    blurDataUrl: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWGRkqGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAQIAEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q==',
}
