import { StudioConfig } from '../types/studio-config'

export const TEST_STUDIO: StudioConfig = {
  slug: 'test-studio',
  name: 'Test Studio',
  tagline: 'Where Neo-Traditional Meets Japanese Mastery',
  artist: 'Alex Test',
  theme: {
    background: '0 0% 3%',
    foreground: '60 9% 98%',
    accent: '14 85% 55%',
    accentForeground: '60 9% 98%',
    mutedForeground: '24 5% 64%',
    dimmedForeground: '12 6% 45%',
    border: '20 6% 15%',
    card: '20 6% 6%',
    accentRgb: '230, 97, 37',
    ring: '14 85% 55%',
  },
  seo: {
    title: 'Test Studio Portland | Neo-Traditional & Japanese Tattoos',
    description: 'Portland\'s premier neo-traditional & Japanese tattoo studio. Custom designs by Alex Test. Book your consultation today. $150-$500 sessions available.',
    keywords: ['neo-traditional tattoo Portland', 'Japanese tattoo Portland'],
    ogTitle: 'Test Studio - Neo-Traditional & Japanese Tattoos in Portland',
    ogDescription: 'Custom neo-traditional and Japanese tattoo designs by Alex Test in Portland. Book your unique tattoo today.',
    siteUrl: 'https://v0-tattoo-artist-website.vercel.app/test-studio',
    ogImageUrl: 'https://placehold.co/1200x630?text=Test%20Studio+OG',
  },
  nav: {
    bookButtonText: 'Book Consultation',
  },
  hero: {
    headlineLine1: 'Neo-Traditional Meets',
    headlineLine2: 'Japanese Artistry',
    subheadline: 'Custom tattoo designs that blend bold neo-traditional elements with timeless Japanese techniques in Portland\'s most authentic studio',
    urgencyText: 'Only 3 consultation slots left this month',
    ctaText: 'Book Your Design Session',
    imageUrl: 'https://placehold.co/800x1000?text=Hero+Image',
    imageAlt: 'Alex Test creating a neo-traditional tattoo design at Test Studio',
  },
  trustMetrics: [
    '8+ Years Experience',
    '1500+ Custom Tattoos',
    '5-Star Google Reviews',
    'Japanese-Trained Artist',
  ],
  portfolio: {
    title: 'Recent Masterpieces',
    subtitle: 'Each tattoo tells a unique story through bold neo-traditional colors and traditional Japanese symbolism',
    images: [
      'https://placehold.co/600x600?text=Portfolio+1',
      'https://placehold.co/600x600?text=Portfolio+2',
      'https://placehold.co/600x600?text=Portfolio+3',
      'https://placehold.co/600x600?text=Portfolio+4',
      'https://placehold.co/600x600?text=Portfolio+5',
      'https://placehold.co/600x600?text=Portfolio+6',
    ],
  },
  sessions: {
    title: 'Tattoo Sessions',
    subtitle: 'Choose the perfect session for your vision, from detailed consultations to full custom pieces',
    guarantee: '100% satisfaction guarantee - if you\'re not completely happy, we\'ll make it right',
    items: [
      {
        title: 'Design Consultation',
        duration: '2-3 hours',
        price: '$150',
        priceSubtitle: 'Applied to final tattoo',
        features: ['Custom design creation', 'Style consultation'],
        availability: 'Available this week',
        buttonText: 'Book Consultation',
      },
      {
        title: 'Full Tattoo Session',
        duration: '4-8 hours',
        price: '$300-$500',
        priceSubtitle: 'Based on size & detail',
        features: ['Complete tattoo execution', 'Aftercare included'],
        availability: '2 week wait',
        buttonText: 'Schedule Session',
      },
    ],
  },
  socialProof: {
    title: 'What Portland Says About Us',
    testimonials: [
      {
        quote: 'Alex\'s neo-traditional style is incredible. The colors pop and the design flows perfectly with my body. Best tattoo experience in Portland!',
        author: 'Sarah M.',
        city: 'Portland',
      },
      {
        quote: 'The Japanese elements in my sleeve are so authentic and detailed. Alex really understands the traditional meanings behind each symbol.',
        author: 'Mike R.',
        city: 'Beaverton',
      },
    ],
    trustBadges: [
      'Licensed & Certified',
      'Sterile Environment',
      'Premium Inks Only',
      'Aftercare Support',
    ],
    instagram: {
      handle: '@teststudio_pdx',
      images: [
        'https://placehold.co/400x400?text=Insta+1',
        'https://placehold.co/400x400?text=Insta+2',
        'https://placehold.co/400x400?text=Insta+3',
        'https://placehold.co/400x400?text=Insta+4',
      ],
    },
  },
  about: {
    title: 'Meet Alex Test',
    paragraph1: 'With over 8 years of dedicated practice, Alex Test has become Portland\'s go-to artist for neo-traditional and Japanese tattoos. After training in traditional Japanese techniques in Kyoto, Alex brings an authentic understanding of symbolism and cultural significance to every piece.',
    paragraph2: 'Specializing in bold neo-traditional designs that incorporate Japanese elements, Alex creates tattoos that are both visually striking and deeply meaningful. Each piece is custom-designed to tell your unique story through the perfect blend of modern artistry and ancient tradition.',
    callout: 'Every tattoo is a collaboration between artist and client, resulting in a truly one-of-a-kind piece of art.',
    imageUrl: 'https://placehold.co/600x800?text=Artist+Portrait',
    imageAlt: 'Alex Test, tattoo artist at Test Studio, working on a neo-traditional design',
  },
  faq: {
    title: 'Frequently Asked Questions',
    items: [
      {
        question: 'How far in advance should I book?',
        answer: 'For consultations, we typically have availability within 1-2 weeks. Full tattoo sessions are usually booked 2-4 weeks out, depending on the size and complexity of your design.',
      },
      {
        question: 'Do you require a deposit?',
        answer: 'Yes, we require a $50 deposit to secure your appointment, which is applied to your final session cost. This ensures we can dedicate the proper time to your custom design.',
      },
    ],
  },
  finalCta: {
    headline: 'Ready to Create Your Masterpiece?',
    subheadline: 'Join the hundreds of satisfied clients who chose Test Studio for their neo-traditional and Japanese tattoos',
    buttonText: 'Start Your Journey',
  },
  booking: {
    modalTitle: 'Book Your Session',
    modalDescription: 'Ready to start your tattoo journey? Fill out the form below and we\'ll get back to you within 24 hours to schedule your consultation.',
    successTitle: 'Booking Request Sent!',
    successMessage: 'Thanks for your interest! We\'ll review your request and get back to you within 24 hours to confirm your appointment.',
    submitText: 'Send Request',
    depositDisclaimer: 'A $50 deposit will be required to confirm your appointment',
  },
  contact: {
    email: 'hello@teststudio.com',
    instagramHandle: '@teststudio_pdx',
    instagramUrl: 'https://instagram.com/teststudio_pdx',
    phone: '(503) 555-0123',
    address: '1234 SE Division St, Portland, OR 97202',
  },
  footer: {
    copyrightHolder: 'Test Studio',
    tagline: 'Neo-Traditional & Japanese Tattoo Artistry in Portland',
  },
  blurDataUrl: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWGRkqGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q==',
}
